
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/bundle"
tap "homebrew/core"

brew "git"
brew "github/gh/gh"
brew "hub"
brew "tig"

brew "nvm"
brew "python"
brew "python@2"
brew "pipenv"
brew "yarn"
brew "wget"
brew "rbenv"
brew "starship"
brew "unrar"
brew "zsh"
brew "zsh-history-substring-search"

brew "mas"

cask "brave-browser"
cask "brooklyn"
cask "dashlane"
cask "discord"
cask "font-jetbrainsmono-nerd-font"
cask "font-jetbrainsmono-nerd-font-mono"
cask "github"
cask "gpg-suite"
cask "iina"
cask "iterm2"
cask "keybase"
cask "now"
cask "postman"
cask "rectangle"
cask "setapp"
cask "steam"
cask "visual-studio-code"
cask "vox"
cask "vox-preferences-pane"
cask "webtorrent"

cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlprettypatch"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-csv"
cask "quicklook-json"
cask "suspicious-package"
cask "webpquicklook"

mas "Bear", id: 1091189122
mas "NordVPN IKE", id: 1116599239
mas "Xcode", id: 497799835
mas "Shazam", id: 897118787