# https://www.nerdfonts.com/cheat-sheet

[character]
# symbol = "λ"
# symbol = "" # lightning symbol
# symbol = "" # flask symbol
symbol = "" # chilli symbol
# symbol = "" # serynge symbol

[nodejs]
# symbol = " "