# https://www.nerdfonts.com/cheat-sheet

[character]
# symbol = "λ"
# symbol = "" # lightning symbol
# symbol = "" # flask symbol
success_symbol = "(bold green)" # chilli symbol
error_symbol = "(bold red)"
# symbol = "" # serynge symbol

[nodejs]
# symbol = " "